package KieRule;
import com.drools.model.IndianCars;

rule "Brezza"

when
ms : IndianCars(model=="Brezza" && brand=="Maruti" && price > 1000000);
then
ms.setDiscount(10);
ms.setFinalPrice(ms.getPrice() - (ms.getPrice()/ms.getDiscount()) );
end;

rule "Swift"

when
ms : IndianCars(model=="Swift" && brand=="Maruti" && price > 1000000);
then
ms.setDiscount(8);
ms.setFinalPrice(ms.getPrice() - (ms.getPrice()/ms.getDiscount()) );
end;

rule "Dzire"

when
ms : IndianCars(model=="Dzire" && brand=="Maruti" && price > 1000000);
then
ms.setDiscount(15);
ms.setFinalPrice(ms.getPrice() - (ms.getPrice()/ms.getDiscount()) );
end;

rule "Creta"

when
ms : IndianCars(model=="Creta" && brand=="Hyundai" && price > 1200000);
then
ms.setDiscount(9);
ms.setFinalPrice(ms.getPrice() - (ms.getPrice()/ms.getDiscount()) );
end;

rule "i20"

when
ms : IndianCars(model=="i20" && brand=="Hyundai" && price > 1200000);
then
ms.setDiscount(7);
ms.setFinalPrice(ms.getPrice() - (ms.getPrice()/ms.getDiscount()) );
end;

rule "Verna"

when
ms : IndianCars(model=="Verna" && brand=="Hyundai" && price > 1200000);
then
ms.setDiscount(14);
ms.setFinalPrice(ms.getPrice() - (ms.getPrice()/ms.getDiscount()) );
end;